apiVersion: v1
kind: Namespace
metadata:
  name: applications
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: applications
spec:
  selector:
    matchLabels:
      run: nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: nginx
        app: nginx
        version: "1.0"
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: applications
  labels:
    run: nginx
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    run: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: applications
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - homelabs.co.in
      secretName: homelabs
  ingressClassName: nginx
  rules:
    - host: homelabs.co.in
      http:
        paths:
          - path: /nginx
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
