---
- name: Add private registry
  hosts: k3s_servers, k3s_agents
  vars:
    registry_file_path: /Users/mradul/Installed/registries.yaml
  tasks:
    - name: Copying private registry file 
      become: true
      copy:
        src: '{{ registry_file_path }}'
        dest: /etc/rancher/k3s/
      register: registry_copied
      
    - name: Reboot host if system settings were updated
      become: yes
      ansible.builtin.reboot:
        reboot_timeout: 3600
      when: registry_copied.changed
